<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.shiftleft</groupId>
    <artifactId>hello-shiftleft</artifactId>
    <version>0.0.1</version>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.1.RELEASE</version>
    </parent>
    <dependencies>
        <dependency>
    		<groupId>commons-io</groupId>
    		<artifactId>commons-io</artifactId>
    		<version>2.14.0</version>
		</dependency>
        <dependency>
    		<groupId>org.apache.httpcomponents</groupId>
    		<artifactId>httpclient</artifactId>
    		<version>4.3.4</version>
		</dependency>
		<dependency>
    		<groupId>org.zeroturnaround</groupId>
    		<artifactId>zt-exec</artifactId>
    		<version>1.9</version>
		</dependency>
        <dependency>
           <groupId>org.jasypt</groupId>
           <artifactId>jasypt</artifactId>
           <version>1.9.2</version>
        </dependency>
        <dependency>
        <groupId>com.github.ulisesbocchio</groupId>
        	<artifactId>jasypt-spring-boot-starter</artifactId>
        	<version>1.11</version>
		</dependency>
    	<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
       <dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
		</dependency>
		<dependency>
			<groupId>org.codehaus.jackson</groupId>
			<artifactId>jackson-mapper-asl</artifactId>
			<version>${jackson.mapper.version}</version>
		</dependency>
	    <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
		    <groupId>org.hsqldb</groupId>
		    <artifactId>hsqldb</artifactId>
		    <scope>runtime</scope>
		</dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
    </dependencies>
    <properties>
        <java.version>1.8</java.version>
        <jackson.mapper.version>1.5.6</jackson.mapper.version>
        <org-springframework.spring-core.version>4.3.20.RELEASE</org-springframework.spring-core.version>
        <org-springframework.spring-webmvc.version>4.3.20.RELEASE</org-springframework.spring-webmvc.version>
        <org-springframework.spring-web.version>4.3.20.RELEASE</org-springframework.spring-web.version>
        <org-springframework.spring-beans.version>4.3.20.RELEASE</org-springframework.spring-beans.version>
        <org-springframework.spring-expression.version>4.3.20.RELEASE</org-springframework.spring-expression.version>
        <org-springframework.spring-context.version>4.3.20.RELEASE</org-springframework.spring-context.version>
        <org-springframework-data.spring-data-commons.version>1.13.12</org-springframework-data.spring-data-commons.version>
        <org-apache-tomcat-embed.tomcat-embed-core.version>8.5.99</org-apache-tomcat-embed.tomcat-embed-core.version>
        <com-fasterxml-jackson-core.jackson-databind.version>2.12.7.1</com-fasterxml-jackson-core.jackson-databind.version>
        <org-hsqldb.hsqldb.version>2.7.1</org-hsqldb.hsqldb.version>
        <org-yaml.snakeyaml.version>1.31</org-yaml.snakeyaml.version>
        <ch-qos-logback.logback-core.version>1.2.13</ch-qos-logback.logback-core.version>
        <ch-qos-logback.logback-classic.version>1.2.13</ch-qos-logback.logback-classic.version>
        <com-fasterxml-jackson-core.jackson-core.version>2.15.0</com-fasterxml-jackson-core.jackson-core.version>
        <org-hibernate.hibernate-core.version>5.3.20.Final</org-hibernate.hibernate-core.version>
        <org-hibernate.hibernate-validator.version>5.3.6.Final</org-hibernate.hibernate-validator.version>
    </properties>
    <build>
        <plugins>
           <plugin>
        		<groupId>org.apache.maven.plugins</groupId>
        		<artifactId>maven-compiler-plugin</artifactId>
        		<version>3.6.1</version>
        		<configuration>
          			<source>1.8</source>
          			<target>1.8</target>
                </configuration>
           </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-core</artifactId>
                <version>${org-springframework.spring-core.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-webmvc</artifactId>
                <version>${org-springframework.spring-webmvc.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-web</artifactId>
                <version>${org-springframework.spring-web.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-beans</artifactId>
                <version>${org-springframework.spring-beans.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-expression</artifactId>
                <version>${org-springframework.spring-expression.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-context</artifactId>
                <version>${org-springframework.spring-context.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-commons</artifactId>
                <version>${org-springframework-data.spring-data-commons.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.tomcat.embed</groupId>
                <artifactId>tomcat-embed-core</artifactId>
                <version>${org-apache-tomcat-embed.tomcat-embed-core.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>${com-fasterxml-jackson-core.jackson-databind.version}</version>
            </dependency>
            <dependency>
                <groupId>org.hsqldb</groupId>
                <artifactId>hsqldb</artifactId>
                <version>${org-hsqldb.hsqldb.version}</version>
            </dependency>
            <dependency>
                <groupId>org.yaml</groupId>
                <artifactId>snakeyaml</artifactId>
                <version>${org-yaml.snakeyaml.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-core</artifactId>
                <version>${ch-qos-logback.logback-core.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${ch-qos-logback.logback-classic.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>${com-fasterxml-jackson-core.jackson-core.version}</version>
            </dependency>
            <dependency>
                <groupId>org.hibernate</groupId>
                <artifactId>hibernate-core</artifactId>
                <version>${org-hibernate.hibernate-core.version}</version>
            </dependency>
            <dependency>
                <groupId>org.hibernate</groupId>
                <artifactId>hibernate-validator</artifactId>
                <version>${org-hibernate.hibernate-validator.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
